import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export const sampleDocuments = [
  {
    id: "doc1",
    name: "Project Proposal - Q1 2024.pdf",
    type: "pdf",
    size: "2.4 MB",
    modified: "2024-02-15",
    created: "2024-02-10",
    folder: "Projects",
    tags: ["proposal", "important", "2024"],
    author: "user1",
    shared: ["user2", "user3"],
    favorited: true,
    content: "This proposal outlines our strategy for Q1 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc2",
    name: "Financial Report Q4 2023.xlsx",
    type: "xlsx",
    size: "1.8 MB",
    modified: "2024-01-20",
    created: "2024-01-15",
    folder: "Finance",
    tags: ["financial", "quarterly", "report"],
    author: "user2",
    shared: ["user1", "user4"],
    favorited: false,
    content: "Quarterly financial data and projections...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc3",
    name: "Team Meeting Notes - Feb 2024.docx",
    type: "docx",
    size: "0.5 MB",
    modified: "2024-02-18",
    created: "2024-02-18",
    folder: "Meetings",
    tags: ["meeting", "notes", "team"],
    author: "user1",
    shared: ["user2", "user3", "user4", "user5"],
    favorited: true,
    content: "Discussion points from our February team meeting...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc4",
    name: "Product Roadmap 2024-2025.pptx",
    type: "pptx",
    size: "3.2 MB",
    modified: "2024-02-05",
    created: "2024-01-25",
    folder: "Projects",
    tags: ["roadmap", "product", "presentation"],
    author: "user3",
    shared: ["user1", "user2"],
    favorited: true,
    content: "Our product development plans for the next 18 months...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc5",
    name: "Employee Handbook 2024.pdf",
    type: "pdf",
    size: "4.7 MB",
    modified: "2024-01-10",
    created: "2024-01-05",
    folder: "HR",
    tags: ["handbook", "policies", "employees"],
    author: "user4",
    shared: ["user1", "user2", "user3", "user5"],
    favorited: false,
    content: "Updated company policies and procedures for 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc6",
    name: "Marketing Strategy - Q1 & Q2.docx",
    type: "docx",
    size: "1.2 MB",
    modified: "2024-02-12",
    created: "2024-02-01",
    folder: "Marketing",
    tags: ["marketing", "strategy", "2024"],
    author: "user5",
    shared: ["user1", "user3"],
    favorited: false,
    content:
      "Marketing initiatives and campaigns planned for first half of 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc7",
    name: "Budget Forecast 2024.xlsx",
    type: "xlsx",
    size: "1.5 MB",
    modified: "2024-01-30",
    created: "2024-01-20",
    folder: "Finance",
    tags: ["budget", "forecast", "financial"],
    author: "user2",
    shared: ["user1", "user4"],
    favorited: true,
    content: "Annual budget projections and allocations...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc8",
    name: "Client Presentation - ABC Corp.pptx",
    type: "pptx",
    size: "2.8 MB",
    modified: "2024-02-20",
    created: "2024-02-15",
    folder: "Sales",
    tags: ["client", "presentation", "sales"],
    author: "user3",
    shared: ["user1", "user5"],
    favorited: false,
    content: "Presentation for our upcoming meeting with ABC Corporation...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc9",
    name: "System Architecture Diagram.png",
    type: "png",
    size: "1.1 MB",
    modified: "2024-02-10",
    created: "2024-02-10",
    folder: "Technical",
    tags: ["architecture", "diagram", "technical"],
    author: "user1",
    shared: ["user3"],
    favorited: false,
    content: "Visual representation of our system architecture...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc10",
    name: "API Documentation.pdf",
    type: "pdf",
    size: "2.2 MB",
    modified: "2024-02-05",
    created: "2024-01-15",
    folder: "Technical",
    tags: ["api", "documentation", "technical"],
    author: "user3",
    shared: ["user1"],
    favorited: true,
    content: "Comprehensive documentation of our API endpoints and usage...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc11",
    name: "Customer Feedback Analysis.xlsx",
    type: "xlsx",
    size: "1.7 MB",
    modified: "2024-02-18",
    created: "2024-02-10",
    folder: "Marketing",
    tags: ["feedback", "analysis", "customers"],
    author: "user5",
    shared: ["user1", "user2"],
    favorited: false,
    content: "Analysis of customer feedback collected in January 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc12",
    name: "Legal Contract - Vendor XYZ.pdf",
    type: "pdf",
    size: "1.3 MB",
    modified: "2024-01-25",
    created: "2024-01-20",
    folder: "Legal",
    tags: ["contract", "legal", "vendor"],
    author: "user4",
    shared: ["user1"],
    favorited: false,
    content: "Service agreement with Vendor XYZ for 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc13",
    name: "Project Timeline.xlsx",
    type: "xlsx",
    size: "0.9 MB",
    modified: "2024-02-22",
    created: "2024-02-15",
    folder: "Projects",
    tags: ["timeline", "project", "schedule"],
    author: "user1",
    shared: ["user2", "user3", "user5"],
    favorited: true,
    content: "Detailed timeline for our Q1 project milestones...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc14",
    name: "Competitive Analysis.docx",
    type: "docx",
    size: "1.4 MB",
    modified: "2024-02-08",
    created: "2024-01-30",
    folder: "Marketing",
    tags: ["competitive", "analysis", "market"],
    author: "user5",
    shared: ["user1", "user3"],
    favorited: false,
    content: "Analysis of our main competitors and market positioning...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc15",
    name: "Onboarding Checklist.pdf",
    type: "pdf",
    size: "0.6 MB",
    modified: "2024-01-15",
    created: "2024-01-10",
    folder: "HR",
    tags: ["onboarding", "checklist", "new hires"],
    author: "user4",
    shared: ["user1", "user2", "user5"],
    favorited: true,
    content: "Step-by-step process for onboarding new team members...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc16",
    name: "Sales Targets Q1 2024.xlsx",
    type: "xlsx",
    size: "0.8 MB",
    modified: "2024-01-10",
    created: "2024-01-05",
    folder: "Sales",
    tags: ["sales", "targets", "quarterly"],
    author: "user3",
    shared: ["user1", "user5"],
    favorited: false,
    content: "Sales goals and targets for Q1 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc17",
    name: "Brand Guidelines.pdf",
    type: "pdf",
    size: "3.5 MB",
    modified: "2024-01-20",
    created: "2023-12-15",
    folder: "Marketing",
    tags: ["brand", "guidelines", "design"],
    author: "user5",
    shared: ["user1", "user2", "user3", "user4"],
    favorited: true,
    content:
      "Official brand guidelines including logo usage, colors, and typography...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc18",
    name: "Database Schema.json",
    type: "json",
    size: "0.3 MB",
    modified: "2024-02-15",
    created: "2024-02-10",
    folder: "Technical",
    tags: ["database", "schema", "technical"],
    author: "user1",
    shared: ["user3"],
    favorited: false,
    content: "JSON representation of our database schema...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc19",
    name: "User Research Results.pptx",
    type: "pptx",
    size: "2.1 MB",
    modified: "2024-02-10",
    created: "2024-02-05",
    folder: "Research",
    tags: ["research", "users", "results"],
    author: "user5",
    shared: ["user1", "user2"],
    favorited: false,
    content: "Findings from our January user research studies...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc20",
    name: "Expense Report - Jan 2024.pdf",
    type: "pdf",
    size: "0.7 MB",
    modified: "2024-02-05",
    created: "2024-02-01",
    folder: "Finance",
    tags: ["expenses", "report", "monthly"],
    author: "user2",
    shared: ["user1", "user4"],
    favorited: false,
    content: "Monthly expense report for January 2024...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc21",
    name: "Code Review Guidelines.md",
    type: "md",
    size: "0.1 MB",
    modified: "2024-01-25",
    created: "2024-01-20",
    folder: "Technical",
    tags: ["code", "review", "guidelines"],
    author: "user3",
    shared: ["user1"],
    favorited: true,
    content: "Best practices and standards for our code review process...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc22",
    name: "Project Kickoff Presentation.pptx",
    type: "pptx",
    size: "1.9 MB",
    modified: "2024-02-20",
    created: "2024-02-18",
    folder: "Projects",
    tags: ["kickoff", "presentation", "project"],
    author: "user1",
    shared: ["user2", "user3", "user4", "user5"],
    favorited: true,
    content: "Presentation for our new project kickoff meeting...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc23",
    name: "Software Requirements Specification.docx",
    type: "docx",
    size: "1.6 MB",
    modified: "2024-02-15",
    created: "2024-02-01",
    folder: "Technical",
    tags: ["requirements", "specification", "software"],
    author: "user3",
    shared: ["user1", "user2"],
    favorited: false,
    content:
      "Detailed requirements specification for our new software release...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
  {
    id: "doc24",
    name: "Training Materials.zip",
    type: "zip",
    size: "5.2 MB",
    modified: "2024-01-30",
    created: "2024-01-25",
    folder: "HR",
    tags: ["training", "materials", "onboarding"],
    author: "user4",
    shared: ["user1", "user5"],
    favorited: false,
    content: "Collection of training materials for new employees...",
    thumbnail: "/placeholder.svg?height=400&width=300",
  },
];

// Folder structure
export const folders = [
  { id: "all", name: "All Documents", icon: "folder" },
  { id: "recent", name: "Recent", count: 12, icon: "clock" },
  { id: "favorited", name: "Favorites", count: 8, icon: "star" },
  { id: "resume", name: "Resume", count: 4, icon: "folder" },
  { id: "trash", name: "Trash", count: 3, icon: "trash" },
];

export const getFileIcon = (type) => {
  switch (type) {
    case "pdf":
      return "file-text";
    case "docx":
      return "file-text";
    case "xlsx":
      return "file-spreadsheet";
    case "pptx":
      return "file-presentation";
    default:
      return "file";
  }
};
